# Generated by Django 4.0.4 on 2023-09-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenprice',
            name='price_url',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
