# Generated by Django 4.0.4 on 2023-10-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_tokenprice_price_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenprice',
            name='price_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
