# Generated by Django 4.0.4 on 2023-12-03 08:08

from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_tokenprice_price_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('private_key', encrypted_model_fields.fields.EncryptedCharField()),
                ('network_type', models.CharField(choices=[('EVM', 'EVM'), ('Solana', 'Solana'), ('Lightning', 'Lightning'), ('NONEVM', 'NONEVM'), ('NONEVMXDC', 'NONEVMXDC')], default='EVM', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain_name', models.CharField(max_length=255)),
                ('chain_id', models.CharField(max_length=255, unique=True)),
                ('native_currency_name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=255)),
                ('decimals', models.IntegerField(default=18)),
                ('explorer_url', models.URLField(blank=True, max_length=255, null=True)),
                ('explorer_api_url', models.URLField(blank=True, max_length=255, null=True)),
                ('explorer_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('rpc_url', models.URLField(blank=True, max_length=255, null=True)),
                ('logo_url', models.URLField(blank=True, max_length=255, null=True)),
                ('modal_url', models.URLField(blank=True, max_length=255, null=True)),
                ('rpc_url_private', models.URLField(max_length=255)),
                ('poa', models.BooleanField(default=False)),
                ('max_gas_price', models.BigIntegerField(default=250000000000)),
                ('gas_multiplier', models.FloatField(default=1)),
                ('enough_fee_multiplier', models.BigIntegerField(default=200000)),
                ('is_testnet', models.BooleanField(default=False)),
                ('chain_type', models.CharField(choices=[('EVM', 'EVM'), ('Solana', 'Solana'), ('Lightning', 'Lightning'), ('NONEVM', 'NONEVM'), ('NONEVMXDC', 'NONEVMXDC')], default='EVM', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chains', to='core.walletaccount')),
            ],
        ),
    ]
