# Generated by Django 4.0.4 on 2023-12-03 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0066_rename_is_one_time_chain_is_one_time_claim'),
        ('core', '0004_walletaccount_chain'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO core_walletaccount (
                id,
                name,
                private_key,
                network_type
            )
            SELECT
                id,
                name,
                private_key,
                network_type
            FROM
                faucet_walletaccount;
            INSERT INTO core_chain (
                id,
                chain_name,
                symbol,
                chain_id,
                rpc_url,
                decimals,
                explorer_url,
                logo_url,
                native_currency_name,
                poa,
                rpc_url_private,
                wallet_id,
                modal_url,
                max_gas_price,
                gas_multiplier,
                chain_type,
                is_testnet,
                is_active,
                enough_fee_multiplier,
                explorer_api_key,
                explorer_api_url  
            )
            SELECT
                id,
                chain_name,
                symbol,
                chain_id,
                rpc_url,
                decimals,
                explorer_url,
                logo_url,
                native_currency_name,
                poa,
                rpc_url_private,
                wallet_id,
                modal_url,
                max_gas_price,
                gas_multiplier,
                chain_type,
                is_testnet,
                is_active,
                enough_fee_multiplier,
                explorer_api_key,
                explorer_api_url
            FROM
                faucet_chain;
            SELECT setval(pg_get_serial_sequence('"core_walletaccount"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "core_walletaccount";
            SELECT setval(pg_get_serial_sequence('"core_chain"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "core_chain";
        """, reverse_sql="")
    ]
