# Generated by Django 4.0.4 on 2024-08-03 07:47

from django.db import migrations, models
import core.fields

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_chain_chain_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='image',
            field=core.fields.CloudflareImagesField(blank=True, null=True, upload_to='', variant='public'),
        ),
    ]
