# Generated by Django 4.0.4 on 2023-05-09 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brightidauraverification',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='brightidmeetverification',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='permission',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
    ]
