# Generated by Django 4.0.4 on 2023-10-26 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0005_onceinalifetimeverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brightidmeetverification',
            name='permission_ptr',
        ),
        migrations.RemoveField(
            model_name='onceinalifetimeverification',
            name='permission_ptr',
        ),
        migrations.RemoveField(
            model_name='oncepermonthverification',
            name='permission_ptr',
        ),
        migrations.RemoveField(
            model_name='onceperweekverification',
            name='permission_ptr',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='polymorphic_ctype',
        ),
        migrations.DeleteModel(
            name='BrightIDAuraVerification',
        ),
        migrations.DeleteModel(
            name='BrightIDMeetVerification',
        ),
        migrations.DeleteModel(
            name='OnceInALifeTimeVerification',
        ),
        migrations.DeleteModel(
            name='OncePerMonthVerification',
        ),
        migrations.DeleteModel(
            name='OncePerWeekVerification',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
