# Generated by Django 4.0.4 on 2023-10-27 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0005_onceinalifetimeverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onceperweekverification',
            name='permission_ptr',
        ),
        migrations.DeleteModel(
            name='OncePerMonthVerification',
        ),
        migrations.DeleteModel(
            name='OncePerWeekVerification',
        ),
    ]
