# Generated by Django 4.0.4 on 2023-10-26 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('permissions', '0006_remove_brightidmeetverification_permission_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='BrightIDAuraVerification',
            fields=[
                ('permission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='permissions.permission')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('permissions.permission',),
        ),
        migrations.CreateModel(
            name='BrightIDMeetVerification',
            fields=[
                ('permission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='permissions.permission')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('permissions.permission',),
        ),
        migrations.CreateModel(
            name='OnceInALifeTimeVerification',
            fields=[
                ('permission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='permissions.permission')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('permissions.permission',),
        ),
    ]
