# Generated by Django 4.0.4 on 2023-10-27 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0006_remove_onceperweekverification_permission_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OncePerMonthVerification',
            fields=[
                ('permission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='permissions.permission')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('permissions.permission',),
        ),
    ]
