# Generated by Django 4.0.4 on 2023-06-07 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faucet', '0046_globalsettings_tokentap_weekly_claim_limit'),
        ('authentication', '0017_alter_userprofile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raffle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('creator', models.CharField(blank=True, max_length=256, null=True)),
                ('creator_url', models.URLField(blank=True, max_length=255, null=True)),
                ('discord_url', models.URLField(blank=True, max_length=255, null=True)),
                ('twitter_url', models.URLField(blank=True, max_length=255, null=True)),
                ('image_url', models.URLField(blank=True, max_length=255, null=True)),
                ('prize', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('max_number_of_entries', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('winner', models.CharField(blank=True, max_length=1024, null=True)),
                ('chain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raffles', to='faucet.chain')),
            ],
        ),
        migrations.CreateModel(
            name='RaffleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signature', models.CharField(blank=True, max_length=1024, null=True)),
                ('nonce', models.BigIntegerField(blank=True, null=True)),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='prizetap.raffle')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raffle_entries', to='authentication.userprofile')),
            ],
            options={
                'unique_together': {('raffle', 'user_profile')},
            },
        ),
    ]
