# Generated by Django 4.0.4 on 2023-06-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prizetap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='is_prize_nft',
            field=models.BooleanField(default=False),
        ),
    ]
