# Generated by Django 4.0.4 on 2023-06-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prizetap', '0002_raffle_is_prize_nft'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='permissions.permission'),
        ),
    ]
