# Generated by Django 4.0.4 on 2023-06-26 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prizetap', '0004_raffle_contract_raffle_raffleid_raffle_signer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raffleentry',
            options={'verbose_name_plural': 'raffle entries'},
        ),
    ]
