# Generated by Django 4.0.4 on 2023-06-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prizetap', '0005_alter_raffleentry_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raffle',
            name='winner',
        ),
        migrations.AddField(
            model_name='raffleentry',
            name='is_winner',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
