# Generated by Django 4.0.4 on 2023-07-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prizetap', '0007_remove_raffleentry_nonce'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffleentry',
            name='tx_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
