# Generated by Django 4.0.4 on 2023-07-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prizetap', '0008_raffleentry_tx_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('BrightIDMeetVerification', 'BrightIDMeetVerification'), ('BrightIDAuraVerification', 'BrightIDAuraVerification')], max_length=255, unique=True)),
                ('response', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='raffle',
            name='permissions',
        ),
        migrations.AddField(
            model_name='raffle',
            name='constraints',
            field=models.ManyToManyField(blank=True, related_name='raffles', to='prizetap.constraint'),
        ),
    ]
