# Generated by Django 4.0.4 on 2023-07-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prizetap', '0009_constraint_remove_raffle_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffleentry',
            name='claiming_prize_tx',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
