# Generated by Django 4.0.4 on 2023-07-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prizetap', '0011_rename_prize_raffle_prize_name_raffle_decimals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffleentry',
            name='multiplier',
            field=models.IntegerField(default=1),
        ),
    ]
