# Generated by Django 4.0.4 on 2023-07-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prizetap', '0013_constraint_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='constraint',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='constraint',
            name='title',
            field=models.CharField(default='User constraint', max_length=255),
            preserve_default=False,
        ),
    ]
