# Generated by Django 4.0.4 on 2023-08-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prizetap', '0014_constraint_description_constraint_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='constraint_params',
            field=models.TextField(blank=True, null=True),
        ),
    ]
