# Generated by Django 4.0.4 on 2023-08-15 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prizetap', '0015_raffle_constraint_params'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raffle',
            name='signer',
        ),
    ]
