# Generated by Django 4.0.4 on 2023-08-15 09:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prizetap', '0017_remove_raffleentry_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='max_multiplier',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='raffle',
            name='start_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
