# Generated by Django 4.0.4 on 2023-08-27 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0053_tokenprice'),
        ('prizetap', '0018_raffle_max_multiplier_raffle_start_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffle',
            name='chain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raffles', to='faucet.chain'),
        ),
    ]
