# Generated by Django 4.0.4 on 2023-09-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prizetap', '0020_alter_raffle_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffle',
            name='deadline',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='max_number_of_entries',
            field=models.IntegerField(),
        ),
    ]
