# Generated by Django 4.0.4 on 2023-09-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prizetap', '0021_alter_raffle_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constraint',
            name='name',
            field=models.CharField(choices=[('BrightIDMeetVerification', 'BrightIDMeetVerification'), ('BrightIDAuraVerification', 'BrightIDAuraVerification'), ('NotHaveUnitapPass', 'NotHaveUnitapPass')], max_length=255, unique=True),
        ),
    ]
