# Generated by Django 4.0.4 on 2023-09-15 20:29

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prizetap', '0024_alter_raffle_prize_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffle',
            name='nft_id',
            field=core.models.BigNumField(blank=True, max_length=200, null=True),
        ),
    ]
