# Generated by Django 4.0.4 on 2023-09-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prizetap', '0025_alter_raffle_nft_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffle',
            name='nft_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
