# Generated by Django 4.0.4 on 2023-10-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prizetap', '0028_remove_raffle_creator_raffle_creator_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constraint',
            name='icon_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
