# Generated by Django 4.0.4 on 2023-10-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prizetap', '0029_constraint_icon_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constraint',
            name='name',
            field=models.CharField(choices=[('BrightIDMeetVerification', 'BrightIDMeetVerification'), ('BrightIDAuraVerification', 'BrightIDAuraVerification'), ('HaveUnitapPass', 'HaveUnitapPass'), ('NotHaveUnitapPass', 'NotHaveUnitapPass'), ('OptimismDonationConstraint', 'OptimismDonationConstraint')], max_length=255, unique=True),
        ),
    ]
