# Generated by Django 4.0.4 on 2023-10-10 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prizetap', '0031_alter_constraint_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineaRaffleEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=255)),
                ('is_winner', models.BooleanField(blank=True, default=False)),
                ('claim_tx', models.CharField(blank=True, max_length=255, null=True)),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linear_entries', to='prizetap.raffle')),
            ],
        ),
    ]
