# Generated by Django 4.0.4 on 2023-10-16 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prizetap', '0032_linearaffleentries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linearaffleentries',
            name='raffle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linea_entries', to='prizetap.raffle'),
        ),
    ]
