# Generated by Django 4.0.4 on 2023-10-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prizetap', '0033_alter_linearaffleentries_raffle'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='vrf_tx_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('VERIFIED', 'Verified'), ('CLOSED', 'Closed'), ('WS', 'Winner is set')], default='PENDING', max_length=10),
        ),
    ]
