# Generated by Django 4.0.4 on 2023-10-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prizetap', '0034_raffle_vrf_tx_hash_alter_raffle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffle',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('VERIFIED', 'Verified'), ('HELD', 'Held'), ('CLOSED', 'Closed'), ('WS', 'Winner is set')], default='PENDING', max_length=10),
        ),
    ]
