# Generated by Django 4.0.4 on 2023-10-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prizetap', '0035_alter_raffle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='winners_count',
            field=models.IntegerField(default=1),
        ),
    ]
