# Generated by Django 4.0.4 on 2023-10-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prizetap', '0036_raffle_winners_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffle',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('VERIFIED', 'Verified'), ('RWS', 'Random words are set'), ('WS', 'Winners are set'), ('CLOSED', 'Closed')], default='PENDING', max_length=10),
        ),
    ]
