# Generated by Django 4.0.4 on 2023-11-09 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prizetap', '0038_alter_constraint_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raffle',
            old_name='nft_id',
            new_name='nft_ids',
        ),
    ]
