# Generated by Django 4.0.4 on 2023-11-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prizetap', '0040_alter_raffle_nft_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='email_url',
            field=models.EmailField(default='blobl@gmail.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='raffle',
            name='necessary_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='raffle',
            name='telegram_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='twitter_url',
            field=models.URLField(default='https://twitter.com/unitap_app', max_length=255),
            preserve_default=False,
        ),
    ]
