# Generated by Django 4.0.4 on 2023-11-20 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prizetap', '0041_raffle_email_url_raffle_necessary_information_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffle',
            name='max_multiplier',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='max_number_of_entries',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='winners_count',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
