# Generated by Django 4.0.4 on 2023-11-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prizetap', '0042_alter_raffle_max_multiplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constraint',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
