# Generated by Django 4.0.4 on 2023-11-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prizetap', '0043_constraint_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='reversed_constraints',
            field=models.TextField(blank=True, null=True),
        ),
    ]
