# Generated by Django 4.0.4 on 2023-12-04 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20231203_0832'),
        ('prizetap', '0044_raffle_reversed_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffle',
            name='chain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raffles', to='core.chain'),
        ),
    ]
