# Generated by Django 4.0.4 on 2023-12-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prizetap', '0045_alter_raffle_chain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffle',
            name='creator_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='description',
            field=models.TextField(),
        ),
    ]
