# Generated by Django 4.0.4 on 2023-11-30 16:50

from django.db import migrations, models


def set_user_wallet(apps, schema_editor):
    RaffleEntry = apps.get_model("prizetap", "RaffleEntry")

    for entry in RaffleEntry.objects.all():
        try:
            entry.user_wallet_address = entry.user_profile.wallets.get(wallet_type="EVM").address
            entry.save()
        except Exception as e:
            print("Error setting user wallet for raffle entries", e)


class Migration(migrations.Migration):
    dependencies = [
        ("prizetap", "0045_raffleentry_user_wallet_alter_raffleentry_raffle_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="raffleentry",
            name="user_wallet",
        ),
        migrations.AddField(
            model_name="raffleentry",
            name="user_wallet_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(set_user_wallet),
    ]
