# Generated by Django 4.0.4 on 2023-11-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prizetap', '0046_remove_raffleentry_user_wallet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffleentry',
            name='user_wallet_address',
            field=models.CharField(max_length=255),
        ),
    ]
