# Generated by Django 4.0.4 on 2024-01-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prizetap', '0046_alter_raffle_creator_name_alter_raffle_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='constraint',
            name='negative_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
