# Generated by Django 4.0.4 on 2023-12-26 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prizetap', '0045_alter_raffle_chain'),
        ('prizetap', '0047_alter_raffleentry_user_wallet_address'),
    ]

    operations = [
    ]
