# Generated by Django 4.0.4 on 2024-01-05 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prizetap', '0047_constraint_negative_description'),
        ('prizetap', '0048_merge_20231226_1046'),
    ]

    operations = [
    ]
