# Generated by Django 4.0.4 on 2024-01-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prizetap', '0050_merge_20240105_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffle',
            name='twitter_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
