# Generated by Django 4.0.4 on 2024-07-01 19:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prizetap', '0060_alter_constraint_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='raffle',
            name='pre_enrollment_file',
            field=models.FileField(blank=True, null=True, upload_to='prizetap/pre_enrollments/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])]),
        ),
        migrations.AddField(
            model_name='raffleentry',
            name='pre_enrollment',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
