# Generated by Django 4.0.4 on 2024-07-12 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0039_lensconnection_farcasterconnection'),
        ('prizetap', '0062_raffle_is_processed_raffle_pre_enrollment_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffleentry',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='raffle_entries', to='authentication.userprofile'),
        ),
    ]
