# Generated by Django 4.0.4 on 2024-07-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prizetap', '0063_alter_raffleentry_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='pre_enrollment_wallets',
            field=models.TextField(blank=True, null=True),
        ),
    ]
