# Generated by Django 5.0 on 2024-08-26 11:54

import cloudflare_images.field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prizetap', '0075_alter_constraint_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffle',
            name='image_url',
            field=cloudflare_images.field.CloudflareImagesField(blank=True, max_length=255, null=True, upload_to='', variant='public'),
        ),
    ]