# Generated by Django 4.0.4 on 2024-08-25 09:12

from django.db import migrations, models


def fix_raffle_images_prefix(apps, schema):
    Raffle = apps.get_model("prizetap", "Raffle")

    raffles = Raffle.objects.all()

    for raffle in raffles:
        if (
            raffle.image
            and raffle.image.name
            and raffle.image.name.startswith("https://imagedelivery.net")
        ):
            # split the url to get the image id
            raffle.image.name = raffle.image.name.split("/")[-2]
            raffle.save()


class Migration(migrations.Migration):

    dependencies = [
        ("tokenTap", "0078_alter_constraint_name"),
    ]

    operations = [
        migrations.RunPython(
            fix_raffle_images_prefix, reverse_code=migrations.RunPython.noop
        )
    ]
