# Generated by Django 4.0.4 on 2022-04-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brightuser',
            name='_verification_status',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'Verified')], default='0', max_length=1),
        ),
    ]
