# Generated by Django 4.0.4 on 2022-04-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0003_brightuser_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brightuser',
            name='address',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
