# Generated by Django 4.0.4 on 2022-04-15 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0004_alter_brightuser_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brightuser',
            name='user',
        ),
    ]
