# Generated by Django 4.0.4 on 2022-04-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0005_remove_brightuser_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=255)),
                ('chain_id', models.CharField(max_length=255, unique=True)),
                ('rpc_url', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
