# Generated by Django 4.0.4 on 2022-04-15 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0006_chain'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('datetime', models.DateTimeField()),
                ('tx_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('bright_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='faucet.brightuser')),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='faucet.chain')),
            ],
        ),
    ]
