# Generated by Django 4.0.4 on 2022-04-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0007_claimreceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='max_claim_amount',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
