# Generated by Django 4.0.4 on 2022-04-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0010_claimreceipt__status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chain',
            old_name='name',
            new_name='chain_name',
        ),
        migrations.AddField(
            model_name='chain',
            name='decimals',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='chain',
            name='explorer_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chain',
            name='logo_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chain',
            name='native_currency_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
