# Generated by Django 4.0.4 on 2022-05-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0011_rename_name_chain_chain_name_chain_decimals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='poa',
            field=models.BooleanField(default=False),
        ),
    ]
