# Generated by Django 4.0.4 on 2022-06-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0012_chain_poa'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='rpc_url_private',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
