# Generated by Django 4.0.4 on 2022-06-07 05:43

from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0013_chain_rpc_url_private'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('private_key', encrypted_model_fields.fields.EncryptedCharField()),
            ],
        ),
        migrations.RemoveField(
            model_name='chain',
            name='wallet_key',
        ),
        migrations.AddField(
            model_name='chain',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chains', to='faucet.walletaccount'),
        ),
    ]
