# Generated by Django 4.0.4 on 2022-06-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0015_chain_fund_manager_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='brightuser',
            name='_sponsored',
            field=models.BooleanField(default=False),
        ),
    ]
