# Generated by Django 4.0.4 on 2022-06-13 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0016_brightuser__sponsored'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chain',
            name='fund_manager_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='chain',
            name='rpc_url_private',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='chain',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chains', to='faucet.walletaccount'),
        ),
    ]
