# Generated by Django 4.0.4 on 2022-08-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0017_alter_chain_fund_manager_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
