# Generated by Django 4.0.4 on 2022-08-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0018_chain_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_chain_claim_limit', models.IntegerField(default=10)),
            ],
        ),
    ]
