# Generated by Django 4.0.4 on 2022-08-22 02:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0018_chain_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='brightuser',
            name='_last_verified_datetime',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc)),
        ),
    ]
