# Generated by Django 4.0.4 on 2022-08-24 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0019_brightuser__last_verified_datetime'),
        ('faucet', '0019_globalsettings'),
    ]

    operations = [
    ]
