# Generated by Django 4.0.4 on 2022-11-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0020_merge_20220824_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='modal_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='claimreceipt',
            name='_status',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'Verified'), ('2', 'Rejected'), ('3', 'Updating')], default='0', max_length=1),
        ),
    ]
