# Generated by Django 4.0.4 on 2022-11-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0021_chain_modal_url_alter_claimreceipt__status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='max_gas_price',
            field=models.BigIntegerField(default=250000000000),
        ),
    ]
