# Generated by Django 4.0.4 on 2022-11-14 06:25

from django.db import migrations, models
import django.db.models.deletion

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("faucet", "0022_chain_max_gas_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                ("tx_hash", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "_status",
                    models.CharField(
                        choices=[
                            ("0", "Pending"),
                            ("1", "Verified"),
                            ("2", "Rejected"),
                        ],
                        default="0",
                        max_length=1,
                    ),
                ),
                (
                    "chain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="faucet.chain",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="claimreceipt",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="claims",
                to="faucet.transactionbatch",
            ),
        ),
    ]
