# Generated by Django 4.0.4 on 2022-11-14 06:25

from django.db import migrations, models
import django.db.models.deletion

from django.db import migrations


def create_batch(apps, schema_editor):
    ClaimReceipt = apps.get_model("faucet", "ClaimReceipt")
    TransactionBatch = apps.get_model("faucet", "TransactionBatch")

    for receipt in ClaimReceipt.objects.exclude(tx_hash=None):
        batch = TransactionBatch.objects.create(
            chain=receipt.chain,
            tx_hash=receipt.tx_hash,
            _status=receipt._status,
        )
        receipt.batch = batch
        receipt.save()


class Migration(migrations.Migration):

    dependencies = [
        ("faucet", "0023_transaction_batch"),
    ]

    operations = [migrations.RunPython(create_batch, migrations.RunPython.noop)]
