# Generated by Django 4.0.4 on 2022-11-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faucet", "0024_copy_tx_hash"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="claimreceipt",
            name="tx_hash",
        ),
        migrations.AlterField(
            model_name="claimreceipt",
            name="_status",
            field=models.CharField(
                choices=[("0", "Pending"), ("1", "Verified"), ("2", "Rejected")],
                default="0",
                max_length=1,
            ),
        ),
    ]
