# Generated by Django 4.0.4 on 2022-11-20 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0025_remove_claimreceipt_tx_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionbatch',
            name='updating',
            field=models.BooleanField(default=False),
        ),
    ]
