# Generated by Django 4.0.4 on 2022-11-28 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0026_transactionbatch_updating'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='gas_multiplier',
            field=models.FloatField(default=1),
        ),
    ]
