# Generated by Django 4.0.4 on 2022-11-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0027_chain_gas_multiplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='needs_funding',
            field=models.BooleanField(default=False),
        ),
    ]
