# Generated by Django 4.0.4 on 2022-12-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0028_chain_needs_funding'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='chain_type',
            field=models.CharField(choices=[('EVM', 'EVM')], default='EVM', max_length=3),
        ),
        migrations.AddField(
            model_name='chain',
            name='is_testnet',
            field=models.BooleanField(default=False),
        ),
    ]
