# Generated by Django 4.0.4 on 2023-02-14 07:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0031_chain_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brightuser',
            name='context_id',
            field=models.CharField(default=uuid.uuid4, max_length=120, unique=True),
        ),
    ]
