# Generated by Django 4.0.4 on 2023-03-12 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_temporarywalletaddress'),
        ('faucet', '0032_remove_claimreceipt_bright_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimreceipt',
            name='bright_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='faucet.brightuser'),
        ),
        migrations.AlterField(
            model_name='claimreceipt',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='authentication.userprofile'),
        ),
    ]
