# Generated by Django 4.0.4 on 2023-02-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0032_alter_brightuser_context_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chain',
            name='chain_type',
            field=models.CharField(choices=[('EVM', 'EVM'), ('SOL', 'SOL')], default='EVM', max_length=3),
        ),
    ]
