# Generated by Django 4.0.4 on 2023-04-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0035_claimreceipt_passive_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chain',
            name='chain_type',
            field=models.CharField(choices=[('EVM', 'EVM'), ('Solana', 'Solana'), ('Lightning', 'Lightning'), ('NONEVM', 'Non-EVM')], default='EVM', max_length=10),
        ),
    ]
