# Generated by Django 4.0.4 on 2023-04-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0036_alter_chain_chain_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chain',
            name='chain_type',
            field=models.CharField(choices=[('EVM', 'EVM'), ('Solana', 'Solana'), ('Lightning', 'Lightning'), ('Non-EVM', 'Non-EVM')], default='EVM', max_length=10),
        ),
    ]
