# Generated by Django 4.0.4 on 2023-04-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0037_alter_chain_chain_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimreceipt',
            name='_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='transactionbatch',
            name='_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
