# Generated by Django 4.0.4 on 2023-04-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0039_alter_chain_chain_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimreceipt',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
