# Generated by Django 4.0.4 on 2023-04-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0040_claimreceipt_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='enough_fee_multiplier',
            field=models.BigIntegerField(default=200000),
        ),
    ]
