# Generated by Django 4.0.4 on 2023-04-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0041_chain_enough_fee_multiplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletaccount',
            name='network_type',
            field=models.CharField(choices=[('EVM', 'EVM'), ('Solana', 'Solana'), ('Lightning', 'Lightning'), ('NONEVM', 'NONEVM')], default='EVM', max_length=10),
        ),
    ]
