# Generated by Django 4.0.4 on 2023-04-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0042_walletaccount_network_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chain',
            name='chain_type',
            field=models.CharField(choices=[('EVM', 'EVM'), ('Solana', 'Solana'), ('Lightning', 'Lightning'), ('NONEVM', 'NONEVM'), ('NONEVMXDC', 'NONEVMXDC')], default='EVM', max_length=10),
        ),
        migrations.AlterField(
            model_name='walletaccount',
            name='network_type',
            field=models.CharField(choices=[('EVM', 'EVM'), ('Solana', 'Solana'), ('Lightning', 'Lightning'), ('NONEVM', 'NONEVM'), ('NONEVMXDC', 'NONEVMXDC')], default='EVM', max_length=10),
        ),
    ]
