# Generated by Django 4.0.4 on 2023-05-07 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0042_lightningconfig'),
        ('faucet', '0043_alter_chain_chain_type_and_more'),
    ]

    operations = [
    ]
