# Generated by Django 4.0.4 on 2023-05-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0044_merge_20230507_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='tokentap_contract_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
