# Generated by Django 4.0.4 on 2023-06-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0046_globalsettings_tokentap_weekly_claim_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='is_gas_tap_available',
            field=models.BooleanField(default=True),
        ),
    ]
