# Generated by Django 4.0.4 on 2023-06-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0047_globalsettings_is_gas_tap_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimreceipt',
            name='already_processed',
            field=models.BooleanField(default=False),
        ),
    ]
