# Generated by Django 4.0.4 on 2023-07-10 17:53

from django.db import migrations
import faucet.models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0049_remove_claimreceipt_already_processed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chain',
            name='max_claim_amount',
            field=faucet.models.BigNumField(max_length=200),
        ),
    ]
