# Generated by Django 4.0.4 on 2023-07-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0051_chain_show_in_gastap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimreceipt',
            name='_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected'), ('Processed', 'Processed'), ('Processed_Rejected', 'Processed_Rejected')], default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='transactionbatch',
            name='_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected'), ('Processed', 'Processed'), ('Processed_Rejected', 'Processed_Rejected')], default='Pending', max_length=30),
        ),
    ]
