# Generated by Django 4.0.4 on 2023-08-27 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_alter_userprofile_username'),
        ('faucet', '0053_tokenprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('total_price', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donation', to='faucet.chain')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='authentication.userprofile')),
            ],
            options={
                'unique_together': {('chain', 'tx_hash')},
            },
        ),
        migrations.DeleteModel(
            name='TokenPrice',
        ),
    ]
