# Generated by Django 4.0.4 on 2023-09-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0054_donationreceipt_delete_tokenprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationreceipt',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected'), ('Processed', 'Processed'), ('Processed_Rejected', 'Processed_Rejected')], default='Processed', max_length=30),
        ),
        migrations.AlterField(
            model_name='donationreceipt',
            name='total_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='donationreceipt',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transactionbatch',
            name='_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected'), ('Processed', 'Processed'), ('Processed_Rejected', 'Processed_Rejected')], db_index=True, default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='transactionbatch',
            name='tx_hash',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
