# Generated by Django 4.0.4 on 2023-10-02 21:42

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0055_donationreceipt_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimreceipt',
            name='amount',
            field=core.models.BigNumField(max_length=200),
        ),
    ]
