# Generated by Django 4.0.4 on 2023-10-24 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0059_chain_explorer_api_key_chain_explorer_api_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globalsettings',
            old_name='weekly_chain_claim_limit',
            new_name='gastap_claim_limit',
        ),
    ]
