# Generated by Django 4.0.4 on 2023-10-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0059_chain_explorer_api_key_chain_explorer_api_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationreceipt',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=30),
        ),
    ]
