# Generated by Django 4.0.4 on 2023-11-08 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0060_alter_donationreceipt_status'),
        ('faucet', '0063_rename_prizetap_weekly_claim_limit_globalsettings_prizetap_round_claim_limit'),
    ]

    operations = [
    ]
