# Generated by Django 4.0.4 on 2023-11-30 14:21
from django.db.models import Q
from django.db import migrations


def set_to_address(apps, schema_editor):
    # set the wallet address in claim receipts
    CR = apps.get_model("faucet", "ClaimReceipt")

    for c in CR.objects.filter(Q(to_address__isnull=True) | Q(to_address="")):
        try:
            c.to_address = c.user_profile.wallets.get(wallet_type="EVM").address
            c.save()
        except Exception as e:
            print("set to_address error", e)


class Migration(migrations.Migration):
    dependencies = [
        ("faucet", "0064_merge_20231108_1331"),
    ]

    operations = [
        migrations.RenameField(
            model_name="claimreceipt",
            old_name="passive_address",
            new_name="to_address",
        ),
        migrations.RunPython(set_to_address),
    ]
