# Generated by Django 4.0.4 on 2023-11-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0064_merge_20231108_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='is_one_time',
            field=models.BooleanField(default=False),
        ),
    ]
