# Generated by Django 4.0.4 on 2023-11-26 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0065_chain_is_one_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chain',
            old_name='is_one_time',
            new_name='is_one_time_claim',
        ),
    ]
