# Generated by Django 4.0.4 on 2023-12-26 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0065_rename_passive_address_claimreceipt_to_address'),
        ('faucet', '0066_rename_is_one_time_chain_is_one_time_claim'),
    ]

    operations = [
    ]
