# Generated by Django 4.0.4 on 2023-12-19 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20231203_0832'),
        ('faucet', '0066_rename_is_one_time_chain_is_one_time_claim'),
    ]

    operations = [
        migrations.RenameModel('Chain', 'Faucet'),
        migrations.RemoveField(
            model_name='faucet',
            name='chain_name',
        ),
        migrations.RemoveField(
            model_name='faucet',
            name='chain_id',
        ),
        migrations.RemoveField(
            model_name='faucet',
            name='native_currency_name',
        ),
        migrations.RemoveField(
            model_name='faucet',
            name='symbol',
        ),
        migrations.RemoveField(
            model_name='faucet',
            name='decimals',
        ),
        migrations.RemoveField(
            model_name='faucet',
            name='explorer_url',
        ),
        migrations.RemoveField(
            model_name='faucet',
            name='explorer_api_url',
        ),
        migrations.RemoveField(
            model_name='faucet',
            name='explorer_api_key',
        ),
        migrations.RemoveField(
            model_name='faucet',
            name='rpc_url',
        ),
        migrations.RemoveField(
            model_name='faucet',
            name='logo_url',
        ),
        migrations.RemoveField(
            model_name='faucet',
            name='modal_url',
        ),
        migrations.RemoveField(
            model_name='faucet',
            name='rpc_url_private',
        ),
        migrations.RemoveField(
            model_name='faucet',
            name='poa',
        ),
        migrations.RemoveField(
            model_name='faucet',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='faucet',
            name='max_gas_price',
        ),
        migrations.RemoveField(
            model_name='faucet',
            name='gas_multiplier',
        ),
        migrations.RemoveField(
            model_name='faucet',
            name='enough_fee_multiplier',
        ),
        migrations.RemoveField(
            model_name='faucet',
            name='is_testnet',
        ),
        migrations.RemoveField(
            model_name='faucet',
            name='chain_type',
        ),
        migrations.AddField(
            model_name='faucet',
            name='chain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='faucets', to='core.chain'),
            preserve_default=False,
        ),
        migrations.RenameField(
            model_name='claimreceipt',
            old_name='chain',
            new_name='faucet'
        ),
        migrations.RenameField(
            model_name='transactionbatch',
            old_name='chain',
            new_name='faucet'
        ),
        migrations.RenameField(
            model_name='donationreceipt',
            old_name='chain',
            new_name='faucet'
        ),
        migrations.AlterUniqueTogether(
            name='donationreceipt',
            unique_together={('faucet', 'tx_hash')},
        ),
    ]
