# Generated by Django 4.0.4 on 2024-01-05 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0067_merge_20231216_1727'),
        ('faucet', '0067_merge_20231226_1046'),
    ]

    operations = [
    ]
