# Generated by Django 4.0.4 on 2024-01-05 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0067_auto_20231219_1401'),
        ('faucet', '0068_merge_20240105_1916'),
    ]

    operations = [
    ]
