# Generated by Django 4.0.4 on 2024-01-05 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0069_merge_20240105_1932'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WalletAccount',
        ),
    ]
