# Generated by Django 4.0.4 on 2024-01-25 09:27
import logging

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.text


def create_donation_contract(apps, schema_editor):
    from core.utils import Web3Utils
    from core.models import NetworkTypes
    faucet = apps.get_model("faucet", "Faucet")
    donation_contract = apps.get_model('faucet', 'DonationContract')

    for f in faucet.objects.filter(chain__chain_type=NetworkTypes.EVM):
        try:
            donation_contract(
                contract_address=Web3Utils.to_checksum_address('0xE6Bc2586fcC1Da738733867BFAf381B846AAe834'),
                faucet=f
            ).save()

        except Exception as e:
            logging.error("create donation contract address error: ", e)


class Migration(migrations.Migration):
    dependencies = [
        ('faucet', '0070_delete_walletaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('contract_address', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('faucet',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donation_contracts',
                                   to='faucet.faucet')),
            ],
        ),
        migrations.AddConstraint(
            model_name='donationcontract',
            constraint=models.UniqueConstraint(django.db.models.expressions.F('faucet'),
                                               condition=models.Q(('deleted__isnull', True)),
                                               name='unique_active_donation_contract'),
        ),
        migrations.AddConstraint(
            model_name='donationcontract',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('contract_address'),
                                               django.db.models.expressions.F('faucet'),
                                               name='unique_donation_contract_address'),
        ),
        migrations.RunPython(create_donation_contract)
    ]
