# Generated by Django 4.0.4 on 2024-01-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0071_donationcontract_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalsettings',
            name='gastap_round_claim_limit',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='is_gas_tap_available',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='prizetap_round_claim_limit',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='tokentap_round_claim_limit',
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='index',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='value',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
