# Generated by Django 4.0.4 on 2024-02-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0072_remove_globalsettings_gastap_round_claim_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faucet',
            name='fuel_level',
            field=models.IntegerField(default=100),
        ),
    ]
