# Generated by Django 4.0.4 on 2024-03-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0073_faucet_fuel_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='faucet',
            name='is_deprecated',
            field=models.BooleanField(default=False),
        ),
    ]
