# Generated by Django 4.0.4 on 2024-05-31 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0074_faucet_is_deprecated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LightningConfig',
        ),
    ]
