# Generated by Django 4.0.4 on 2024-04-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0074_faucet_is_deprecated'),
    ]

    operations = [
        migrations.AddField(
            model_name='faucet',
            name='total_claims_since_last_round',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faucet',
            name='total_claims_this_round',
            field=models.IntegerField(default=0),
        ),
    ]
