# Generated by Django 4.0.4 on 2024-06-11 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0075_delete_lightningconfig'),
        ('faucet', '0075_faucet_total_claims_since_last_round_and_more'),
    ]

    operations = [
    ]
