# Generated by Django 4.0.4 on 2024-06-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0075_delete_lightningconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='faucet',
            name='total_claims_since_last_round',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='faucet',
            name='total_claims_this_round',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
