# Generated by Django 4.0.4 on 2024-06-24 13:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0076_faucet_total_claims_since_last_round_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faucet',
            name='used_unitap_pass_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
