# Generated by Django 4.0.4 on 2024-07-17 13:18

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0077_faucet_used_unitap_pass_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faucet',
            name='used_unitap_pass_list',
            field=core.models.UniqueArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None, unique=True),
        ),
    ]
