# Generated by Django 4.0.4 on 2023-02-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_wallet_remove_evmwallet_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='address',
            field=models.CharField(default=0, max_length=512, unique=True),
            preserve_default=False,
        ),
    ]
