# Generated by Django 4.0.4 on 2023-02-28 13:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0006_wallet_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='UserProfile',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='profile',
            new_name='user_profile',
        ),
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together={('wallet_type', 'user_profile')},
        ),
    ]
