# Generated by Django 4.0.4 on 2023-03-08 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_userprofile_user_alter_wallet_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryWalletAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=512, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_wallet', to='authentication.userprofile')),
            ],
        ),
    ]
