# Generated by Django 4.0.4 on 2023-03-23 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_temporarywalletaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 3, 23, 13, 7, 20, 593792)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_type',
            field=models.CharField(choices=[('EVM', 'EVM Wallet'), ('Solana', 'Solana Wallet'), ('Lightning', 'Lightning Wallet'), ('Non-EVM', 'Non-EVM Wallet')], max_length=10),
        ),
    ]
