# Generated by Django 4.0.4 on 2023-03-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_userprofile_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_type',
            field=models.CharField(choices=[('EVM', 'EVM Wallet'), ('Solana', 'Solana Wallet'), ('Lightning', 'Lightning Wallet'), ('NONEVM', 'Non-EVM Wallet')], max_length=10),
        ),
        migrations.DeleteModel(
            name='TemporaryWalletAddress',
        ),
    ]
