# Generated by Django 4.0.4 on 2023-05-10 09:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_userprofile_username_alter_wallet_wallet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Username can only contain letters, digits and @/./+/-/_.', regex='^[\\w.@+-]+$')]),
        ),
    ]
