# Generated by Django 4.0.4 on 2023-10-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_alter_userprofile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_temporary',
            field=models.BooleanField(default=False),
        ),
    ]
