# Generated by Django 4.0.4 on 2023-09-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_alter_userprofile_username'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together={('wallet_type', 'address')},
        ),
        migrations.AddField(
            model_name='wallet',
            name='primary',
            field=models.BooleanField(default=False),
        ),
    ]
