# Generated by Django 4.0.4 on 2023-11-26 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_alter_wallet_unique_together'),
        ('authentication', '0020_remove_userprofile_is_new_by_wallet'),
    ]

    operations = [
    ]
