# Generated by Django 4.0.4 on 2023-11-30 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_merge_20231126_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='primary',
        ),
    ]
