# Generated by Django 4.0.4 on 2023-12-20 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_alter_userprofile_initial_context_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrightIDConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('context_id', models.CharField(max_length=512, unique=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='authentication.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
