# Generated by Django 4.0.4 on 2024-01-08 16:14

from django.db import migrations, models
import django.db.models.expressions
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0026_wallet_deleted_wallet_deleted_by_cascade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='address',
            field=models.CharField(max_length=512),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('address'), condition=models.Q(('deleted__isnull', True)), name='unique_wallet_address'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('address'), django.db.models.expressions.F('user_profile'), name='unique_wallet_user_profile_address'),
        ),
    ]
