# Generated by Django 4.0.4 on 2024-04-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0033_twitterconnection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterconnection',
            name='access_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='twitterconnection',
            name='access_token_secret',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
