# Generated by Django 4.0.4 on 2024-05-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0035_ensconnection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_type',
            field=models.CharField(choices=[('EVM', 'EVM'), ('Solana', 'Solana'), ('NONEVM', 'NONEVM'), ('NONEVMXDC', 'NONEVMXDC')], max_length=10),
        ),
    ]
