# Generated by Django 4.0.4 on 2024-07-23 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0039_lensconnection_farcasterconnection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brightidconnection',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='authentication.userprofile', unique=True),
        ),
        migrations.AlterField(
            model_name='ensconnection',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='authentication.userprofile', unique=True),
        ),
        migrations.AlterField(
            model_name='farcasterconnection',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='authentication.userprofile', unique=True),
        ),
        migrations.AlterField(
            model_name='gitcoinpassportconnection',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='authentication.userprofile', unique=True),
        ),
        migrations.AlterField(
            model_name='lensconnection',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='authentication.userprofile', unique=True),
        ),
        migrations.AlterField(
            model_name='twitterconnection',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='authentication.userprofile', unique=True),
        ),
    ]
