# Generated by Django 4.0.4 on 2024-08-05 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0040_alter_brightidconnection_user_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brightidconnection',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='authentication.userprofile'),
        ),
        migrations.AlterField(
            model_name='ensconnection',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='authentication.userprofile'),
        ),
        migrations.AlterField(
            model_name='farcasterconnection',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='authentication.userprofile'),
        ),
        migrations.AlterField(
            model_name='gitcoinpassportconnection',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='authentication.userprofile'),
        ),
        migrations.AlterField(
            model_name='lensconnection',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='authentication.userprofile'),
        ),
        migrations.AlterField(
            model_name='twitterconnection',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='authentication.userprofile'),
        ),
    ]
