# Generated by Django 4.0.4 on 2024-08-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0041_alter_brightidconnection_user_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitterconnection',
            name='twitter_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
