# Generated by Django 4.0.4 on 2024-04-04 18:35

import core.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0031_userprofile_is_verified'),
        ('core', '0005_auto_20231203_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor', models.CharField(blank=True, max_length=127, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('holding', 'Holding'), ('finished', 'Finished')], default='not_started', max_length=20)),
                ('prize_amount', core.models.BigNumField(max_length=200)),
                ('token', models.CharField(max_length=100)),
                ('token_address', models.CharField(max_length=255)),
                ('discord_url', models.URLField(blank=True, max_length=255, null=True)),
                ('twitter_url', models.URLField(blank=True, max_length=255, null=True)),
                ('email_url', models.EmailField(max_length=255)),
                ('telegram_url', models.URLField(blank=True, max_length=255, null=True)),
                ('image_url', models.URLField(blank=True, max_length=255, null=True)),
                ('rest_time_seconds', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(5)])),
                ('token_image_url', models.URLField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competitions', to='core.chain')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('answer_time_limit_seconds', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(5)])),
                ('text', models.TextField()),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiztap.competition')),
            ],
            options={
                'unique_together': {('competition', 'number')},
            },
        ),
        migrations.CreateModel(
            name='UserCompetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_winner', models.BooleanField(default=False)),
                ('amount_won', core.models.BigNumField(blank=True, max_length=200, null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiztap.competition')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='quiztap.question')),
                ('selected_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='quiztap.choice')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='authentication.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='competition',
            name='participants',
            field=models.ManyToManyField(related_name='participated_competitions', through='quiztap.UserCompetition', to='authentication.userprofile'),
        ),
        migrations.AddField(
            model_name='competition',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='held_competitions', to='authentication.userprofile'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quiztap.question'),
        ),
    ]
