# Generated by Django 4.0.4 on 2024-04-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0031_userprofile_is_verified'),
        ('quiztap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='rest_time_seconds',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer_time_limit_seconds',
        ),
        migrations.AlterField(
            model_name='competition',
            name='status',
            field=models.CharField(choices=[('not_started', 'NOT_STARTED'), ('in_progress', 'IN_PROGRESS'), ('finished', 'FINISHED')], default='not_started', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('user_profile', 'question')},
        ),
    ]
