# Generated by Django 4.0.4 on 2024-04-05 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0032_gitcoinpassportconnection'),
        ('quiztap', '0002_remove_competition_rest_time_seconds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_answer', to='quiztap.question'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='selected_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_answer', to='quiztap.choice'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_answer', to='authentication.userprofile'),
        ),
    ]
