# Generated by Django 4.0.4 on 2024-04-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiztap', '0003_alter_useranswer_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('FINISHED', 'Finished')], default='NOT_STARTED', max_length=20),
        ),
    ]
