# Generated by Django 4.0.4 on 2024-04-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiztap', '0005_alter_useranswer_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_can_be_shown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='can_be_shown',
            field=models.BooleanField(default=False),
        ),
    ]
