# Generated by Django 4.0.4 on 2024-04-06 23:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('quiztap', '0006_question_answer_can_be_shown_question_can_be_shown'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='title',
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
    ]
