# Generated by Django 4.0.4 on 2024-04-07 00:41

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiztap', '0007_competition_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercompetition',
            name='amount_won',
            field=core.models.BigNumField(default=0, max_length=200),
        ),
    ]
