# Generated by Django 4.0.4 on 2024-04-08 13:39

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiztap', '0008_alter_usercompetition_amount_won'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='amount_won',
            field=core.models.BigNumField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='competition',
            name='winner_count',
            field=models.IntegerField(default=0),
        ),
    ]
