# Generated by Django 4.0.4 on 2024-04-15 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sponsor'),
        ('quiztap', '0010_alter_competition_sponsor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competitions', to='core.sponsor'),
        ),
    ]
