# Generated by Django 4.0.4 on 2024-08-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sponsor_image'),
        ('quiztap', '0011_alter_competition_sponsor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='sponsor',
        ),
        migrations.AddField(
            model_name='competition',
            name='sponsor',
            field=models.ManyToManyField(blank=True, related_name='competitions', to='core.sponsor'),
        ),
    ]
