# Generated by Django 4.0.4 on 2023-09-11 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learntap', '0002_mission_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tags',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='name',
        ),
    ]
