# Generated by Django 4.0.4 on 2023-09-11 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learntap', '0003_rename_tags_tag_rename_tag_tag_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tag',
            new_name='Tagasdf',
        ),
    ]
