# Generated by Django 4.0.4 on 2023-09-11 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learntap', '0004_rename_tag_tagasdf'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tagasdf',
            new_name='Tag',
        ),
    ]
