# Generated by Django 4.0.4 on 2023-09-12 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_alter_userprofile_username'),
        ('learntap', '0005_rename_tagasdf_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refferal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refferals', to='learntap.mission')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refferals_recieved', to='authentication.userprofile')),
                ('referred_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referals_made', to='authentication.userprofile')),
            ],
        ),
    ]
