# Generated by Django 4.0.4 on 2023-09-12 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_alter_userprofile_username'),
        ('learntap', '0007_referral_delete_refferal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='referral',
            new_name='Referral3',
        ),
    ]
