# Generated by Django 4.0.4 on 2023-09-12 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_alter_userprofile_username'),
        ('learntap', '0008_rename_referral_referral3'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Referral3',
            new_name='Referral',
        ),
    ]
