# Generated by Django 4.0.4 on 2023-09-12 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learntap', '0009_rename_referral3_referral'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('imageUrl', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='learntap.mission')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('mission', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('task_type', models.CharField(blank=True, choices=[('article', 'Article'), ('video', 'Video'), ('quiz', 'Quiz')], max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('imageUrl', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('definition', models.TextField(blank=True, null=True)),
                ('has_action', models.BooleanField(default=False)),
                ('action_button_text', models.CharField(blank=True, default='Verify', max_length=200, null=True)),
                ('verifications_definition', models.TextField(blank=True, null=True)),
                ('XP', models.IntegerField(default=0)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='learntap.mission')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='learntap.station')),
                ('verifications', models.ManyToManyField(blank=True, to='learntap.constraint')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('mission', 'station', 'order')},
            },
        ),
    ]
