# Generated by Django 4.0.4 on 2023-09-12 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_alter_userprofile_username'),
        ('learntap', '0010_station_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTaskProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user_data', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learntap.task')),
            ],
            options={
                'ordering': ['started_at'],
                'unique_together': {('profile', 'task')},
            },
        ),
        migrations.CreateModel(
            name='UserMissionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('current_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learntap.task')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learntap.mission')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile')),
            ],
            options={
                'unique_together': {('profile', 'mission')},
            },
        ),
    ]
