# Generated by Django 4.0.4 on 2023-09-12 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learntap', '0011_usertaskprogress_usermissionprogress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertaskprogress',
            options={},
        ),
        migrations.RemoveField(
            model_name='usertaskprogress',
            name='started_at',
        ),
    ]
