# Generated by Django 4.0.4 on 2023-05-09 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faucet', '0045_chain_tokentap_contract_address'),
        ('authentication', '0016_userprofile_username_alter_wallet_wallet_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('distributer', models.CharField(max_length=100)),
                ('distributer_url', models.URLField(blank=True, max_length=255, null=True)),
                ('discord_url', models.URLField(blank=True, max_length=255, null=True)),
                ('twitter_url', models.URLField(blank=True, max_length=255, null=True)),
                ('image_url', models.URLField(blank=True, max_length=255, null=True)),
                ('token', models.CharField(max_length=100)),
                ('token_address', models.CharField(max_length=255)),
                ('amount', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_distribution', to='faucet.chain')),
            ],
        ),
        migrations.CreateModel(
            name='TokenDistributionClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signed_typed_data', models.TextField()),
                ('token_distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='tokenTap.tokendistribution')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokentap_claims', to='authentication.userprofile')),
            ],
        ),
    ]
