# Generated by Django 4.0.4 on 2023-05-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
        ('tokenTap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokendistribution',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='permissions.permission'),
        ),
    ]
