# Generated by Django 4.0.4 on 2023-05-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenTap', '0002_tokendistribution_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokendistribution',
            name='max_number_of_claims',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
