# Generated by Django 4.0.4 on 2023-05-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenTap', '0004_tokendistribution_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokendistributionclaim',
            name='signed_typed_data',
        ),
        migrations.AddField(
            model_name='tokendistributionclaim',
            name='nonce',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tokendistributionclaim',
            name='signature',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
