# Generated by Django 4.0.4 on 2023-05-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenTap', '0005_remove_tokendistributionclaim_signed_typed_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokendistributionclaim',
            name='nonce',
        ),
        migrations.RemoveField(
            model_name='tokendistributionclaim',
            name='signature',
        ),
        migrations.AddField(
            model_name='tokendistributionclaim',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
