# Generated by Django 4.0.4 on 2023-05-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenTap', '0006_remove_tokendistributionclaim_nonce_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokendistributionclaim',
            name='nonce',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tokendistributionclaim',
            name='signature',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
