# Generated by Django 4.0.4 on 2023-05-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenTap', '0007_tokendistributionclaim_nonce_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokendistributionclaim',
            name='signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
