# Generated by Django 4.0.4 on 2023-05-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenTap', '0008_alter_tokendistributionclaim_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokendistributionclaim',
            name='signature',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
