# Generated by Django 4.0.4 on 2023-05-20 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokenTap', '0009_alter_tokendistributionclaim_signature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tokendistribution',
            old_name='distributer',
            new_name='distributor',
        ),
        migrations.RenameField(
            model_name='tokendistribution',
            old_name='distributer_url',
            new_name='distributor_url',
        ),
    ]
