# Generated by Django 4.0.4 on 2023-06-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenTap', '0011_tokendistribution_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokendistributionclaim',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='tokendistributionclaim',
            name='tx_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
