# Generated by Django 4.0.4 on 2023-06-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenTap', '0012_tokendistributionclaim_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokendistributionclaim',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected'), ('Processed', 'Processed')], default='Pending', max_length=10),
        ),
    ]
