# Generated by Django 4.0.4 on 2023-07-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenTap', '0013_alter_tokendistributionclaim_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokendistributionclaim',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected'), ('Processed', 'Processed'), ('Processed_Rejected', 'Processed_Rejected')], default='Pending', max_length=30),
        ),
    ]
