# Generated by Django 4.0.4 on 2023-08-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenTap', '0016_alter_constraint_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokendistribution',
            name='token_image_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
