# Generated by Django 4.0.4 on 2023-10-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenTap', '0017_tokendistribution_token_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='constraint',
            name='icon_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
