# Generated by Django 4.0.4 on 2023-12-05 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20231203_0832'),
        ('tokenTap', '0022_constraint_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokendistribution',
            name='chain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_distribution', to='core.chain'),
        ),
    ]
