# Generated by Django 4.0.4 on 2023-12-02 15:01

from django.db import migrations, models


def set_user_wallet(apps, schema_editor):
    tdc = apps.get_model("tokenTap", "TokenDistributionClaim")

    for entry in tdc.objects.all():
        try:
            if entry.token_distribution.chain.chain_type == "EVM":
                entry.user_wallet_address = entry.user_profile.wallets.get(
                    wallet_type="EVM"
                ).address
                entry.save()
            elif entry.token_distribution.chain.chain_type == "LIGHTNING":
                entry.user_wallet_address = entry.signature
                entry.save()
        except Exception as e:
            print("Error setting user wallet for tdc", e)


class Migration(migrations.Migration):
    dependencies = [
        ("tokenTap", "0022_constraint_explanation"),
    ]

    operations = [
        migrations.AddField(
            model_name="tokendistributionclaim",
            name="user_wallet_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(set_user_wallet),
    ]
