# Generated by Django 4.0.4 on 2023-12-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenTap', '0023_alter_tokendistribution_chain'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokendistribution',
            name='contract',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
