# Generated by Django 4.0.4 on 2024-01-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenTap', '0024_tokendistribution_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='constraint',
            name='negative_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
