# Generated by Django 4.0.4 on 2023-12-26 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokenTap', '0023_tokendistributionclaim_user_wallet_address'),
        ('tokenTap', '0024_tokendistribution_contract'),
    ]

    operations = [
    ]
