# Generated by Django 4.0.4 on 2024-01-05 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokenTap', '0025_merge_20231216_1727'),
        ('tokenTap', '0026_merge_20240105_1905'),
    ]

    operations = [
    ]
