# Generated by Django 4.0.4 on 2024-01-09 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokenTap', '0027_merge_20240105_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tokendistribution',
            old_name='permissions',
            new_name='constraints',
        ),
    ]
