# Generated by Django 4.0.4 on 2024-01-10 13:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tokenTap', '0028_rename_permissions_tokendistribution_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokendistribution',
            name='email_url',
            field=models.EmailField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tokendistribution',
            name='necessary_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tokendistribution',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tokendistribution',
            name='start_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tokendistribution',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('VERIFIED', 'Verified')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='tokendistribution',
            name='telegram_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tokendistribution',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
