# Generated by Django 4.0.4 on 2024-01-10 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0028_remove_wallet_unique_wallet_address_and_more'),
        ('tokenTap', '0029_tokendistribution_email_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokendistribution',
            name='distributor_address',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tokendistribution',
            name='distributor_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='token_distributions', to='authentication.userprofile'),
            preserve_default=False,
        ),
    ]
