# Generated by Django 4.0.4 on 2024-01-13 08:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenTap', '0030_tokendistribution_distributor_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokendistribution',
            name='constraint_params',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tokendistribution',
            name='reversed_constraints',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='constraint',
            name='name',
            field=models.CharField(choices=[('core.BrightIDMeetVerification', 'BrightIDMeetVerification'), ('core.BrightIDAuraVerification', 'BrightIDAuraVerification'), ('core.HasNFTVerification', 'HasNFTVerification'), ('tokenTap.OncePerMonthVerification', 'OncePerMonthVerification'), ('tokenTap.OnceInALifeTimeVerification', 'OnceInALifeTimeVerification'), ('faucet.OptimismHasClaimedGasInThisRound', 'OptimismHasClaimedGasInThisRound')], max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='tokendistribution',
            name='amount',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tokendistribution',
            name='constraints',
            field=models.ManyToManyField(blank=True, related_name='token_distributions', to='tokenTap.constraint'),
        ),
        migrations.AlterField(
            model_name='tokendistribution',
            name='distributor',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tokendistribution',
            name='max_number_of_claims',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tokendistribution',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tokendistribution',
            name='notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
