# Generated by Django 4.0.4 on 2024-02-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenTap', '0033_globalsettings_alter_constraint_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokendistribution',
            name='distribution_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
