# Generated by Django 4.0.4 on 2024-02-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenTap', '0035_tokendistribution_tx_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokendistribution',
            name='decimals',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
