# Generated by Django 4.0.4 on 2024-03-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenTap', '0038_alter_constraint_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokendistribution',
            name='is_one_time_claim',
            field=models.BooleanField(default=True),
        ),
    ]
