# Generated by Django 4.0.4 on 2024-03-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenTap', '0040_alter_constraint_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='constraint',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
