# Generated by Django 4.0.4 on 2024-07-11 10:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenTap', '0048_alter_constraint_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokendistribution',
            name='used_unitap_pass_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='tokendistributionclaim',
            name='is_unitap_pass_share',
            field=models.BooleanField(default=False),
        ),
    ]
