# Generated by Django 5.0 on 2024-08-26 10:22

import cloudflare_images.field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokenTap', '0061_alter_constraint_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokendistribution',
            name='image_url',
        ),
        migrations.AddField(
            model_name='tokendistribution',
            name='image',
            field=cloudflare_images.field.CloudflareImagesField(blank=True, upload_to='', variant='custom'),
        ),
    ]
