# Generated by Django 5.0 on 2024-10-05 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0042_twitterconnection_twitter_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("user_id", models.BigIntegerField()),
                ("first_name", models.CharField(blank=True, max_length=255, null=True)),
                ("last_name", models.CharField(blank=True, max_length=255, null=True)),
                ("username", models.CharField(blank=True, max_length=600, null=True)),
                (
                    "user_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s",
                        to="authentication.userprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
