# Generated by Django 5.1.2 on 2024-10-17 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramconnection',
            options={'permissions': [('can_broadcast', 'Can broadcast messages')]},
        ),
    ]
